services:
  # 1. The Database Service
  db:
    image: postgres:15-alpine
    container_name: notes_db_container
    restart: always
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notes_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # 2. The Backend Service
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  # 3. The Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

# Define the volume for the DB
volumes:
  db_data: